map_type: costmap

obstacle_range: 3.0
raytrace_range: 3.0

transform_tolerance: 0.2

inflation_radius: 1.5
footprint: [[0.2, 0.175], [-0.2, 0.175], [-0.2, -0.175], [0.2, -0.175]]
observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: hokuyo, data_type: LaserScan, topic: /udacity_bot/laser/scan, marking: true, clearing: true}
