map_type: costmap

obstacle_range: 3.0
raytrace_range: 3.0

transform_tolerance: 0.2

inflation_radius: 1.4
footprint: [[0.17, 0.15], [-0.17, 0.15], [-0.17, -0.15], [0.17, -0.15]]
observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: hokuyo, data_type: LaserScan, topic: /new_robot/laser/scan, marking: true, clearing: true}
